sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: MsmCQAfsRKqUUPM2/wb5C/W55gi/5IL+ZUKqKbcp3uPnEXzdszqKNiK54I6JC4RTik55UlApBqtJTnZCwtunfH4dQgw/c3REfYMF34Chp8Wws0gMw9IlDnQ7G3mDJtDzwjTThBWkrDvBQvhbkWYm96I256KWcCxIsvVpk0+oASvmScU1PYDi5HoMyBvrqlasBHF6FgF3B80PXjXEx+M0vktVtOTupNJfDyCxDLbgg3+EZiwj6/f8fzfqNjUyAd/oEr9KCpeijqy5LMtm89t5yF6nha/QA5RLUoI3hcNmzWt2cCiOrw4tD4q2HLTdh1s45r7KEe80O0gnHiZ4Vlggv61OEnSQfWUgk/jkbnaAK6ARHHTtYLTg9uRlgMHuyDbUP6sI1AHm2rF3U19LaytMsCscBR++bGWPEgIzzA7TjmnDFT3K5dKOhzx4A4WMqSEEFRTG/1quUY4FeeHwYSOlJVqcM8aovHLMXBl29q+GSWXtkY+XwQbSImHOQP/Ujg5iimILaOo3f2PQbMcvlCnvyEh7mLd+rYXfeQpP5UeSjk5YY5stSdHYcXvrpxRT1U4XR5b/6wpzLFoDLMsvQQlWtLX2VgpvCZtsO+v/VBxyFJL2iq6LFlUsF35vR3u7uCJ0XzffxNapp5PHQEjiYA5wIrtkRLett3CZkfjAfJhS0MQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Cavalry-General_1172
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy